# Generated by Django 3.2.5 on 2021-07-29 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210729_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='contry',
            new_name='country',
        ),
    ]
